# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

- templates: BuildWindows.yaml
  parameters:
    platform: Windows
    architecture: Win32
    configuration: RelWithDebInfo

- template: BuildWindows.yaml
  parameters:
    platform: Windows
    architecture: x64
    configuration: RelWithDebInfo

- template: BuildWindows.yaml
  parameters:
    platform: Windows
    architecture: ARM
    configuration: RelWithDebInfo

- template: BuildWindows.yaml
  parameters:
    platform: Windows
    architecture: ARM64
    configuration: RelWithDebInfo

- template: BuildWindows.yaml
  parameters:
    platform: WindowsStore
    architecture: Win32
    configuration: RelWithDebInfo

- template: BuildWindows.yaml
  parameters:
    platform: WindowsStore
    architecture: x64
    configuration: RelWithDebInfo

- template: BuildAndroid.yaml
  parameters:
    configuration: RelWithDebInfo
    architecture: armeabi-v7a
    jobName: arm

- template: BuildAndroid.yaml
  parameters:
    configuration: RelWithDebInfo
    architecture: arm64-v8a
    jobName: arm64

- template: BuildAndroid.yaml
  parameters:
    configuration: RelWithDebInfo
    architecture: x86
    jobName: x86