# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

jobs:
- job: Unity_Packaging
  workspace:
    clean: all
  continueOnError: false
  displayName: Generating Unity, NuGet and NPM Packages
  pool:
    name: Analog On-Prem
    demands: Unity2019.1.10f1
  variables:
    unityLocation: ''
  steps:
  - script: echo Downloading Pipeline Artifacts
  - checkout: self
    submodules: true
  - task: DownloadPipelineArtifact@2
    inputs:
      artifactName: 'BuildArtifacts'
      buildType: 'current'
      targetPath: '$(Pipeline.Workspace)'
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script:
        $info = (Get-UnitySetupInstance | Select-UnitySetupInstance -Version $(UnityVersion)).Path + "\Editor";
        Write-Output "##vso[task.setvariable variable=unityLocation;]$info"
  - task: PowerShell@2
    name: SetVersionTag
    condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      targetType: 'inline'
      script:
        Write-Output "##vso[task.setvariable variable=ProductVersion;]$(ProductVersion)"
  - script: python tools\unity_package.py -u "$(unityLocation)" -s $(Pipeline.Workspace) -o "$(Pipeline.Workspace)\unity" -v $(ProductVersion)
    displayName: Building Unity Package
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Unity Package to Fileshare'
    inputs:
      PathtoPublish: '$(Pipeline.Workspace)\unity'
      ArtifactName: IsacPluginUnity
      publishLocation: FilePath
      TargetPath: '$(InternalFileShare)\$(Build.SourceBranchName)\$(Build.BuildNumber)\'
      Parallel: true
  - script: python tools\nuget_package.py -s $(Pipeline.Workspace) -o "$(Pipeline.Workspace)\nuget" -v $(ProductVersion)
    displayName: Building NuGet Package
  - task: PublishBuildArtifacts@1
    displayName: 'Publish NuGet Package to Fileshare'
    inputs:
      PathtoPublish: '$(Pipeline.Workspace)\nuget'
      ArtifactName: IsacPluginNuget
      publishLocation: FilePath
      TargetPath: '$(InternalFileShare)\$(Build.SourceBranchName)\$(Build.BuildNumber)\'
      Parallel: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish NuGet Package to Build Artifacts'
    inputs:
      PathtoPublish: '$(Pipeline.Workspace)\nuget'
      ArtifactName: 'NugetPackage'
  - task: NodeTool@0
    displayName: 'Install NPM Tools'
  - task: npmAuthenticate@0
    displayName: NPM Authenticate
    inputs:
      workingFile: Source\Plugins\IsacPluginGenerator\Assets\Microsoft.SpatialAudio.Spatializer.Unity\.npmrc
  - script: python tools\upm_package.py -s $(Pipeline.Workspace) -o "$(Pipeline.Workspace)\npm" -v $(ProductVersion)
    displayName: Build NPM Package
  - task: PublishBuildArtifacts@1
    displayName: 'Publish NPM Package to Fileshare'
    inputs:
      PathtoPublish: '$(Pipeline.Workspace)\npm'
      ArtifactName: IsacPluginNpm
      publishLocation: FilePath
      TargetPath: '$(InternalFileShare)\$(Build.SourceBranchName)\$(Build.BuildNumber)\'
      Parallel: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish NPM Package to Build Artifacts'
    inputs:
      PathtoPublish: '$(Pipeline.Workspace)\npm'
      ArtifactName: 'NpmPackage'
  - powershell: Test-Path '$(Pipeline.Workspace)\npm\$(NpmPackageName)-$(ProductVersion).tgz'

