# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

jobs:
- deployment: Publish
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], variables['SigningBranch']))
  continueOnError: false
  displayName: Publish Packages to Feeds
  pool:
    name: Analog On-Prem
  environment: 'SpatialAudio-Unity Release Approval'
  strategy:
    runOnce:
      deploy:
        steps:
        - script: echo Syncing Source
        - checkout: self
          submodules: true
        - task: CmdLine@2
          displayName: Copy .npmrc for Public Feed
          inputs:
            script: copy $(Build.SourcesDirectory)\Tools\PublicFeed.npmrc $(Build.SourcesDirectory)\Source\Plugins\CrossPlatformPluginGenerator\Assets\Microsoft.SpatialAudio.Spatializer.Unity\.npmrc
        - task: npmAuthenticate@0
          displayName: Public NPM Feed Authentication
          inputs:
            workingFile: Source\Plugins\CrossPlatformPluginGenerator\Assets\Microsoft.SpatialAudio.Spatializer.Unity\.npmrc
            customEndpoint: 'aipmr MixedReality-Unity-Packages'
        - script: python tools\upm_package.py -s $(Pipeline.Workspace)\BuildArtifacts -o $(Pipeline.Workspace)\npm -v $(ProductVersion) -p
          displayName: Publish NPM Package to Public UPM Feed
